import React from 'react';
import type { Metadata } from 'next';
import {
	defaultLocale,
	getDictionary,
	isValidLocale,
	type Locale,
} from '@/dictionaries';

interface LayoutProps {
	children: React.ReactNode;
	params: Promise<{ language: string }>;
}

export async function generateMetadata({
	params,
}: {
	params: Promise<{ language: string }>;
}): Promise<Metadata> {
	const { language } = await params;
	const locale: Locale = isValidLocale(language) ? language : defaultLocale;
	const dictionary = await getDictionary(locale);

	return {
		title: dictionary.linkPageTitle,
		description: 'Generated by create next app',
	};
}

export default function RootLayout({
	children,
}: Readonly<LayoutProps>) {
	return (
		<div>
			<div>{children}</div>
		</div>
	);
}
