services:
  personal-homepage-standalone:
    build:
      context: .
      dockerfile: Dockerfile
    image: personal-homepage-image
    container_name: personal-homepage-container
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped