import React from 'react';
import type { Metadata } from 'next';
import {
	defaultLocale,
	getDictionary,
	isValidLocale,
	type Locale,
} from '@/dictionaries';
import LeftTopPage from './left-top/page';
import LeftBottomPage from './left-bottom/page';
import RightTopPage from './right-top/page';
import RightBottomPage from './right-bottom/page';
import styles from './layout.module.css';

interface LayoutProps {
	children: React.ReactNode;
	params: Promise<{ language: string }>;
}

export async function generateMetadata({
	params,
}: {
	params: Promise<{ language: string }>;
}): Promise<Metadata> {
	const { language } = await params;
	const locale: Locale = isValidLocale(language) ? language : defaultLocale;
	const dictionary = await getDictionary(locale);

	return {
		title: dictionary.profilePageTitle,
		description: 'Generated by create next app',
	};
}

export default function RootLayout({
	children,
}: Readonly<LayoutProps>) {
	return (
		<div className={styles.profileLayout}>
			<div className={styles.profileGrid}>
				<div className={styles.leftColumn}>
					<LeftTopPage />
					<LeftBottomPage />
				</div>
				<div className={styles.rightColumn}>
					<RightTopPage />
					<RightBottomPage />
				</div>
			</div>

			<div className={styles.children}>{children}</div>
		</div>
	);
}
