import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import {
	defaultLocale,
	getDictionary,
	isValidLocale,
	type Locale,
} from '@/dictionaries';

export async function generateMetadata({
	params,
}: {
	params: Promise<{ language: string }>;
}): Promise<Metadata> {
	const { language } = await params;
	const locale: Locale = isValidLocale(language) ? language : defaultLocale;
	const dictionary = await getDictionary(locale);

	return {
		title: dictionary.aboutPageTitle,
		description: 'Generated by create next app',
	};
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return children;
}
